export const fieldLabels: Record<string, string> = {
  sheetId: "Sheet ID",
  sheetName: "Datasheet Name",
  sheetDesc: "Datasheet Description",
  sheetDesc2: "Additional Description",
  clientDocNum: "Client Document #",
  clientProjectNum: "Client Project #",
  companyDocNum: "Company Document #",
  companyProjectNum: "Company Project #",
  areaId: "Area",
  areaName: "Area",
  packageName: "Package Name",
  revisionNum: "Revision Number",
  revisionDate: "Revision Date",
  preparedById: "Prepared By",
  preparedByName: "Prepared By",
  preparedByDate: "Prepared Date",
  verifiedById: "Verified By",
  verifiedByName: "Verified By",
  verifiedDate: "Verified Date",
  approvedById: "Approved By",
  approvedByName: "Approved By",
  approvedDate: "Approved Date",
  rejectedById: "Rejected By",
  rejectedByName: "Rejected By",
  rejectedByDate: "Rejected Date",
  modifiedById: "Modified By",
  modifiedByName: "Modified By",
  modifiedByDate: "Modified Date",
  status: "Status",
  isLatest: "Is Latest Version",
  isTemplate: "Is Template",
  rejectComment: "Rejection Comment",
  equipmentName: "Equipment Name",
  equipmentTagNum: "Equipment Tag",
  serviceName: "Service Name",
  requiredQty: "Required Quantity",
  itemLocation: "Item Location",
  manuId: "Manufacturer",
  manuName: "Manufacturer Name",
  suppId: "Supplier",
  suppName: "Supplier Name",
  installPackNum: "Installation Package #",
  equipSize: "Equipment Size",
  modelNum: "Model Number",
  driver: "Driver Type",
  locationDwg: "Location Drawing",
  pid: "PID #",
  installDwg: "Installation Drawing",
  codeStd: "Code/Standard",
  categoryId: "Category",
  categoryName: "Category",
  clientId: "Client",
  clientName: "Client Name",
  projectId: "Project",
  projectName: "Project Name",
  templateId: "Template ID",
  parentSheetId: "Parent Sheet ID",
  autoCADImport: "Imported from AutoCAD",
  sourceFilePath: "Source File Path",
};
