/**
 * Canonical permission keys. Must match dbo.Permissions.PermissionKey (see docs/phase2.5-roles-permissions.md).
 * No extra keys; use DATASHEET_* for both templates and filled sheets; use ESTIMATION_VIEW/ESTIMATION_EDIT (not ESTIMATIONS_VIEW/ESTIMATION_UPDATE).
 */
export const PERMISSIONS = {
  DATASHEET_CREATE: "DATASHEET_CREATE",
  DATASHEET_VIEW: "DATASHEET_VIEW",
  DATASHEET_EDIT: "DATASHEET_EDIT",
  DATASHEET_VERIFY: "DATASHEET_VERIFY",
  DATASHEET_APPROVE: "DATASHEET_APPROVE",
  DATASHEET_NOTE_EDIT: "DATASHEET_NOTE_EDIT",
  DATASHEET_ATTACHMENT_UPLOAD: "DATASHEET_ATTACHMENT_UPLOAD",
  DATASHEET_ATTACHMENT_DELETE: "DATASHEET_ATTACHMENT_DELETE",
  DATASHEET_EXPORT: "DATASHEET_EXPORT",

  REVISIONS_VIEW: "REVISIONS_VIEW",

  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  ESTIMATION_CREATE: "ESTIMATION_CREATE",
  ESTIMATION_VIEW: "ESTIMATION_VIEW",
  ESTIMATION_EDIT: "ESTIMATION_EDIT",
  ESTIMATION_EXPORT: "ESTIMATION_EXPORT",

  INVENTORY_CREATE: "INVENTORY_CREATE",
  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_EDIT: "INVENTORY_EDIT",
  INVENTORY_DELETE: "INVENTORY_DELETE",
  INVENTORY_MAINTENANCE_VIEW: "INVENTORY_MAINTENANCE_VIEW",
  INVENTORY_MAINTENANCE_CREATE: "INVENTORY_MAINTENANCE_CREATE",
  INVENTORY_TRANSACTION_CREATE: "INVENTORY_TRANSACTION_CREATE",
} as const;
