export const PERMISSIONS = {
  TEMPLATE_CREATE: "TEMPLATE_CREATE",
  TEMPLATES_VIEW: "TEMPLATES_VIEW",
  TEMPLATE_VIEW: "TEMPLATE_VIEW",
  TEMPLATE_UPDATE: "TEMPLATE_UPDATE",
  TEMPLATE_VERIFY: "TEMPLATE_VERIFY",
  TEMPLATE_APPROVE: "TEMPLATE_APPROVE",
  TEMPLATE_REJECT: "TEMPLATE_REJECT",

  DATASHEET_CREATE: "DATASHEET_CREATE",
  DATASHEETS_VIEW: "DATASHEETS_VIEW",
  DATASHEET_VIEW: "DATASHEET_VIEW",
  DATASHEET_UPDATE: "DATASHEET_UPDATE",
  DATASHEET_VERIFY: "DATASHEET_VERIFY",
  DATASHEET_APPROVE: "DATASHEET_APPROVE",
  DATASHEET_REJECT: "DATASHEET_REJECT",

  REVISIONS_VIEW: "REVISIONS_VIEW",

  ESTIMATION_CREATE: "ESTIMATION_CREATE",
  ESTIMATIONS_VIEW: "ESTIMATIONS_VIEW",
  ESTIMATION_VIEW: "ESTIMATION_VIEW",
  ESTIMATION_UPDATE: "ESTIMATION_UPDATE",
  ESTIMATION_VERIFY: "ESTIMATION_VERIFY",
  ESTIMATION_APPROVE: "ESTIMATION_APPROVE",
  ESTIMATION_REJECT: "ESTIMATION_REJECT",

  INVENTORY_CREATE: "INVENTORY_CREATE",
  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_UPDATE: "INVENTORY_UPDATE",
  INVENTORY_DELETE: "INVENTORY_DELETE",
};
