name: Backend CI

on:
  push:
    branches: [main, beta-1.0]
  pull_request:
    branches: [main, beta-1.0]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --ext .ts

      - name: Type check with TypeScript
        run: npx tsc --noEmit

      - name: Run backend tests (Jest)
        run: npm run test
